### ISSUE TITLE
webpack issue

### ISSUE THREAD

**Issue by po5i** [jfmdev/simple-spellchecker#10]
after `yarn add simple-spellchecker` I have some issues working with may webpack stack (I'm webpack noob tho)

Using Electron and React

When using `var SpellChecker = require('simple-spellchecker');` on any component I got:

```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (webpack:///./~/natives/index.js?:44:62)
    at eval (webpack:///./~/natives/index.js?:44:140)
    at Array.forEach (native)
    at Object.req [as require] (webpack:///./~/natives/index.js?:39:15)
    at eval (webpack:///./~/unzip/~/graceful-fs/fs.js?:1:73)
    at Object../node_modules/unzip/node_modules/graceful-fs/fs.js (file:///Users/xxx/React/yarn-app/dll/vendor.dll.js:25821:1)
    at __webpack_require__ (file:///Users/xxx/React/yarn-app/dll/vendor.dll.js:21:30)
    at eval (webpack:///./~/unzip/~/graceful-fs/graceful-fs.js?:3:27)
    at Object../node_modules/unzip/node_modules/graceful-fs/graceful-fs.js (file:///Users/xxx/React/yarn-app/dll/vendor.dll.js:25828:1)
    at __webpack_require__ (file:///Users/xxx/React/yarn-app/dll/vendor.dll.js:21:30)
```

When using  `var SpellChecker = require('simple-spellchecker');` on the main process as documented, everything goes fine, until I begin the build package (mac in my case)... I got something strange:

```
7543ms building modules                                                                  
23ms sealing
1ms optimizing 
0ms basic module optimization 
6ms module optimization 
1ms advanced module optimization 
0ms basic chunk optimization 
0ms chunk optimization 
1ms advanced chunk optimization 
2ms module and chunk tree optimization 
16ms module reviving
18ms module order optimization
6ms module id optimization 
5ms chunk reviving 
0ms chunk order optimization 
13ms chunk id optimization
18ms hashing
1ms module assets processing 
49ms chunk assets processing
2ms additional chunk assets processing 
0ms recording 
5352ms additional asset processing
1168ms chunk asset optimization
1ms asset optimization 
113ms emitting
Hash: 38bcebeadc96325befb5
Version: webpack 2.4.1
Time: 14298ms
            Asset     Size  Chunks                    Chunk Names
    ./app/main.js  1.95 MB       0  [emitted]  [big]  main
./app/main.js.map  2.29 MB       0  [emitted]         main
[./app/main.development.js] ./app/main.development.js 11.7 kB {0} [built]
       [] -> factory:89ms building:356ms = 445ms
[./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
       [] -> factory:84ms building:40ms = 124ms
[./node_modules/babel-polyfill/node_modules/core-js/fn/regexp/escape.js] ./~/babel-polyfill/~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
       [] -> factory:258ms building:76ms = 334ms
[./node_modules/babel-polyfill/node_modules/core-js/shim.js] ./~/babel-polyfill/~/core-js/shim.js 7.38 kB {0} [built]
       [] -> factory:257ms building:93ms dependencies:562ms = 912ms
[./node_modules/electron-debug/index.js] ./~/electron-debug/index.js 2.19 kB {0} [built]
       [] -> factory:838ms building:1139ms dependencies:108ms = 2085ms
[./node_modules/electron-devtools-installer/dist/index.js] ./~/electron-devtools-installer/dist/index.js 4.63 kB {0} [built]
       [] -> factory:850ms building:1261ms dependencies:0ms = 2111ms
[./node_modules/electron-is-dev/index.js] ./~/electron-is-dev/index.js 154 bytes {0} [built]
       [] -> factory:837ms building:1146ms = 1983ms
[./node_modules/electron-localshortcut/index.js] ./~/electron-localshortcut/index.js 3.33 kB {0} [built]
       [] -> factory:967ms building:212ms dependencies:0ms = 1179ms
[./node_modules/electron-updater/out/main.js] ./~/electron-updater/out/main.js 4.72 kB {0} [built]
       [] -> factory:849ms building:1250ms dependencies:3ms = 2102ms
[./node_modules/regenerator-runtime/runtime.js] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
       [] -> factory:253ms building:53ms = 306ms
[./node_modules/simple-spellchecker/dictionary.js] ./~/simple-spellchecker/dictionary.js 6.12 kB {0} [built]
       [] -> factory:37ms building:813ms = 850ms
  [20] multi babel-polyfill ./app/main.development 40 bytes {0} [built]
        factory:1ms building:2ms = 3ms
[./node_modules/simple-spellchecker/index.js] ./~/simple-spellchecker/index.js 7.86 kB {0} [built]
       [] -> factory:843ms building:1238ms dependencies:0ms = 2081ms
[./node_modules/source-map-support/source-map-support.js] ./~/source-map-support/source-map-support.js 16.4 kB {0} [built]
       [] -> factory:835ms building:1109ms dependencies:1ms = 1945ms
[./package.json] ./package.json 8.57 kB {0} [built]
       [] -> factory:1244ms building:12ms = 1256ms
    + 560 hidden modules

WARNING in ./~/natives/index.js
44:17-28 Critical dependency: the request of a dependency is an expression

ERROR in unknown: Invalid number (55946:17)

npm ERR! Darwin 16.7.0
```

I think it's something related to `natives`.

**Comment by jfmdev** [comment]
Hi Carlos, I have not tested this library with _Webpack_ (it's in the roadmap, but it may take a while till I do it), nor with _Yarn_ (although it should work, since Yarn is supposed to work with npm modules), so perhaps you should visit a Webpack-related forum
