### ISSUE TITLE
dictionary.spellCheck() returns incorrect result for sv-SE

### ISSUE THREAD

**Issue by raczkowskimateusz** [jfmdev/simple-spellchecker#52]
Hi,
I'm trying to use a spell checker for Swedish language. I see some words are not working properly. For example:

- `node cli.js check "./dict" sv-SE närstående`
- `node cli.js check "./dict" sv-SE månad`
- `node cli.js check "./dict" sv-SE hur`

All of these words are correct in Swedish (also exists in sv-SE.dic file). But in results I have:

- `{ misspelled: true, suggestions: [] }`
- `{ misspelled: true, suggestions: [ 'myntad', 'murad' ] }`
- `{ misspelled: true, suggestions: [ 'häl', 'hål', 'hal', 'haj', 'håg' ] }`

**Comment by jfmdev** [comment]
Hi @raczkowskimateusz,

Sorry for the late response.

Unfortunately, I was unable to reproduce the issue you are describing: when I execute the commands you mention, I get successful responses.

```
node cli.js check "./dict" sv-SE närstående
{ misspelled: false, suggestions: [ 'närståendes' ] }

node cli.js check "./dict" sv-SE månad
{
  misspelled: false,
  suggestions: [ 'manad', 'månade', 'måna', 'månads' ]
}

node cli.js check "./dict" sv-SE hur
{ misspelled: false, suggestions: [ 'huru', 'hus', 'hut', 'huv' ] }
```

Which environment  (i.e. command line application, operating systema and Node version) are you using to run the commands?

> From my part, I'm running the commands using `cmd.exe`, on Windows 11, and using Node 20.10.0.

**Comment by raczkowskimateusz** [comment]
Hi @jfmdev 
I have checked a few nodes (16.14.2, 18.18.0, 20.10.0), and I have same issue on each of them. I'm using `PowerShell` but on `cmd` I have the same problem.

The only difference is that I'm using Windows 10 for this.

**Comment by jfmdev** [comment]
@raczkowskimateusz Since I can't reproduce the issue locally, I can't debug it, but I have three guesses (that maybe you can try on your end):

1. The dictionary isn't being read correctly because either (a) the dictionary file is defective or (b) due a bug in Node.
3. The [binarysearch](https://www.npmjs.com/package/binarysearch) library has a bug that prevents finding the word within the dictionary.
4. The [damerau-levenshtein](https://www.npmjs.com/package/damerau-levenshtein) library has a bug that prevents calculating correctly the _distance_ between two words.

----

**1)** Have you tried using `dictionary.spellCheck()` for other languages?  
Because if the spell checker works correctly for "ru-RU" and "lt-LT", but fails for "sv-SE", that could be an indication that the dictionary file for Swedish is defective  
But if the spell checker works for languages like "en-US" / "es-MX" (languages whose words are mainly ASCII characters) but fails for languages like "ru-RU" and "lt-LT", but fails for "sv-SE", that could be an indication that Node has a problem with special characters.

For test this you could modify the file `cli.js` (on the line 27) to add a line to print the first 20 words, and check if the words are printed correctly:

```js
// Verify if must check a word.
if(action == 'check') {
    // Read parameters.
    var inputFolder = process.argv.length > 3? process.argv[3] : null;
    var fileName = process.argv.length > 4? process.argv[4] : null;
    var word = process.argv.length > 5? process.argv[5] : null;
    
    // Get dictionary.
    SpellChecker.getDictionary(fileName, inputFolder, function(err, res) {
        // Show result.
        if(err) {
            console.log(err);
        } else {
            var dictionary = res;

            // DEBUG CODE (start)
            for(var i=0; i<20; i++) console.log(dictionary.wordlist[i])
            // DEBUG CODE (end)

            console.log(dictionary.checkAndSuggest(word));
        }
        
        // Close process.
        process.exit();
    });
}
```

-----

**2)** To check if the "binarysearch" library is working correctly, you can modify the file `cli.js` (on the line 12)  to add a code that does some simple search, and check if it produces the expected result:

```js
// Read action.
var action = process.argv.length > 2? process.argv[2].toLowerCase() : '';

// DEBUG CODE (start)
const BinarySearch = require('binarysearch');
var Collator = new Intl.Collator(undefined, {'sensitivity': 'accent'});
var res1 = BinarySearch(
	["närmiljös", "närradio", "närstående", "närvarit", "nasarens"], // Haystack
	"närstående", // Needle
	Collator.compare // Comparison method
);
console.log("Binary Search result for 'närstående': " + res1  + " (expected value is 2)");
var res2 = BinarySearch(
	["målningarnas", "måltiden", "mammas", "månad", "murad", "musköts", "myntad"], // Haystack
	"månad", // Needle
	Collator.compare // Comparison method
);
console.log("Binary Search result for 'månad': " + res2  + " (expected value is 3)");
// DEBUG CODE (end)

// Verify if must check a word.
if(action == 'check') {
```

----

**3)**  To check if the "damerau-levenshtein" library is working correctly, you can modify the file `cli.js` (on the line 12)  to add a code that does some simple comparisons, and check if it produces the expected result:

```js
// Read action.
var action = process.argv.length > 2? process.argv[2].toLowerCase() : '';

// DEBUG CODE (start)
const Levenshtien  = require('damerau-levenshtein');
var tests = [
  { first: 'närstående', second: "närstående", expected: 0 },
  { first: 'närstående', second: "närsynt", expected: 5 },
  { first: 'närstående', second: "närvarit", expected: 7 },
  { first: 'månad', second: "månad", expected: 0 },
  { first: 'månad', second: "murad", expected: 2 },
  { first: 'månad', second: "musköts", expected: 6 },
  { first: 'månad', second: "myntad", expected: 2 },
];
for(var i=0; i<tests.length; i++) {
  var dist = Levenshtien(tests[i].first, tests[i].second).steps; 
  console.log(
	"Levenshten distance for '" + 
	tests[i].first + 
	"' and '" + 
	tests[i].second + 
	"' is: " + 
	dist + 	
	" (expected result is: " + 
	tests[i].expected + 
	")" 
  )
}
// DEBUG CODE (end)

// Verify if must check a word.
if(action == 'check') {
```

**Comment by raczkowskimateusz** [comment]
Hi,
1) I have checked a `ru-RU`, `pl-PL` and other words for `sv-SE`
For `ru-RU` it looks correct:

```
node cli.js check "./dict" ru-RU Нет
-де
-ка
-либо
-нибудь
-с
-таки
-то
а
а-конто
а-ля
а.л.
аарона
ааронов
аб
аба
абажур
абажура
абажурам
абажурами
абажурах
{ misspelled: false, suggestions: [ 'нета', 'нете', 'нети', 'неся' ] }```

node cli.js check "./dict" ru-RU Спасибо
-де
-ка
-либо
-нибудь
-с
-таки
-то
а
а-конто
а-ля
а.л.
аарона
ааронов
аб
аба
абажур
абажура
абажурам
абажурами
абажурах
{
  misspelled: false,
  suggestions: [ 'спасиби', 'спаси', 'спасите', 'спасёно' ]
```

For `pl-PL` it not always correct.
`więc` and `dziękuję` are correct words in Polish.
```
node cli.js check "./dict" pl-PL więc
a
A
aa
AA
aaa
Aalto
AAP
Aara
Aarą
Aare
Aarę
Aargau
Aaro
Aaron
Aarona
Aaronach
Aaronami
Aaronem
Aaronie
Aaronom
{ misspelled: true, suggestions: [ 'wizy', 'wizo' ] }
```

```
node cli.js check "./dict" pl-PL dziękuję
a
A
aa
AA
aaa
Aalto
AAP
Aara
Aarą
Aare
Aarę
Aargau
Aaro
Aaron
Aarona
Aaronach
Aaronami
Aaronem
Aaronie
Aaronom
{ misspelled: true, suggestions: [ 'dziwuję' ] }
```

but for other words with special characters its ok:
```
node cli.js check "./dict" pl-PL łatwo
a
A
aa
AA
aaa
Aalto
AAP
Aara
Aarą
Aare
Aarę
Aargau
Aaro
Aaron
Aarona
Aaronach
Aaronami
Aaronem
Aaronie
Aaronom
{
  misspelled: false,
  suggestions: [ 'łatwy', 'łatwi', 'łatwe', 'łatwą' ]
}
```


I've checked also some simple word in Swedish:  `natt` and I have a wrong result:
```
node cli.js check "./dict" sv-SE natt
å
åar
åarna
åarnas
åars
åbäka
åbäkade
åbäkar
åbäkat
åbäke
åbäkes
åbäket
åbäkets
abbé
abbedissa
abbedissan
abbedissans
abbedissas
abbedissor
abbedissorna
{
  misspelled: true,
  suggestions: [ 'naket', 'naivt', 'naiv', 'namn', 'napp' ]
}
```

but for other simple swedish word: `tack` is correct:
```
node cli.js check "./dict" sv-SE Tack
å
åar
åarna
åarnas
åars
åbäka
åbäkade
åbäkar
åbäkat
åbäke
åbäkes
åbäket
åbäkets
abbé
abbedissa
abbedissan
abbedissans
abbedissas
abbedissor
abbedissorna
{ misspelled: false, suggestions: [ 'täck', 'tacka', 'tacks', 'tak' ] }
```

2. I still have a wrong results:
```
node cli.js check "./dict" sv-SE månad
Binary Search result for 'närstående': 2 (expected value is 2)
Binary Search result for 'månad': 3 (expected value is 3)
{ misspelled: true, suggestions: [ 'myntad', 'murad' ] }

node cli.js check "./dict" sv-SE närstående
Binary Search result for 'närstående': 2 (expected value is 2)
Binary Search result for 'månad': 3 (expected value is 3)
{ misspelled: true, suggestions: [] }
```

3. Here I also have a wrong results:
```
node cli.js check "./dict" sv-SE närstående
Levenshten distance for 'närstående' and 'närstående' is: 0 (expected result is: 0)
Levenshten distance for 'närstående' and 'närsynt' is: 5 (expected result is: 5)
Levenshten distance for 'närstående' and 'närvarit' is: 7 (expected result is: 7)
Levenshten distance for 'månad' and 'månad' is: 0 (expected result is: 0)
Levenshten distance for 'månad' and 'murad' is: 2 (expected result is: 2)
Levenshten distance for 'månad' and 'musköts' is: 6 (expected result is: 6)
Levenshten distance for 'månad' and 'myntad' is: 2 (expected result is: 2)
{ misspelled: true, suggestions: [] }

node cli.js check "./dict" sv-SE månad
Levenshten distance for 'närstående' and 'närstående' is: 0 (expected result is: 0)
Levenshten distance for 'närstående' and 'närsynt' is: 5 (expected result is: 5)
Levenshten distance for 'närstående' and 'närvarit' is: 7 (expected result is: 7)
Levenshten distance for 'månad' and 'månad' is: 0 (expected result is: 0)
Levenshten distance for 'månad' and 'murad' is: 2 (expected result is: 2)
Levenshten distance for 'månad' and 'musköts' is: 6 (expected result is: 6)
Levenshten distance for 'månad' and 'myntad' is: 2 (expected result is: 2)
{ misspelled: true, suggestions: [ 'myntad', 'murad' ] }
```



I ran tests but I have 2 fails also:
```
npm test

> simple-spellchecker@1.0.2 test
> mocha test.js



  Module methods
    √ getDictionary() (55ms)
    √ getDictionarySync()

  Dictionary methods
    spellCheck()
      √ should return true for 'December'
      √ should return true for 'december'
      √ should return true for 'house'
      √ should return true for 'a'
      1) should return true for 'zymurgy'
      √ should return true for "Zorro's"
      √ should return false for 'housec'
      √ should return false for 'decembe'
    isMisspelled()
      √ should return false for 'December'
      √ should return false for 'december'
      √ should return false for 'house'
      √ should return false for 'a'
      2) should return false for 'zymurgy'
      √ should return false for "Zorro's"
      √ should return true for 'housec'
      √ should return true for 'decembe'
    getSuggestions()
      √ should get suggestions for 'house'
      √ should get suggestions for 'housec'
    checkAndSuggest()
      √ should return true and get suggestions for 'house'
      √ should return false and get suggestions for 'housec'
    addRegex() and clearRegexs()
      √ should validate numbers
      √ should validate emails
      √ should validate URLs


  23 passing (158ms)
  2 failing

  1) Dictionary methods
       spellCheck()
         should return true for 'zymurgy':
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:64:59)
      at processImmediate (node:internal/timers:466:21)

  2) Dictionary methods
       isMisspelled()
         should return false for 'zymurgy':
     AssertionError: expected true to be false
      at Context.<anonymous> (test.js:91:61)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by jfmdev** [comment]
@raczkowskimateusz Thanks for running the tests, I think we can discard that the issue is related to either special characters, the "binarysearch" library or the "damerau-levenshtein" library.

My only guess is that maybe the dictionaries aren't normalized in your system.

----------

For test that, you can run commands:

* `node cli.js normalize "./dict/sv-SE.dic"`
* `node cli.js normalize "./dict/en-US.dic"`

> That will normalize the Swedish and English dictionaries.

And then run again:

* `node cli.js check "./dict" sv-SE månad`
* `node cli.js check "./dict" sv-SE närstående`
* `node cli.js check "./dict" en-US zymurgy`

**Comment by raczkowskimateusz** [comment]
Hi @jfmdev 
Thanks for commands, it looks correct right now.
First, I executed the command:
`node cli.js normalize "./dict/sv-SE.dic"`

Then I ran the commands again. Results are correct:

```
 node cli.js check "./dict" sv-SE närstående
 { misspelled: false, suggestions: [ 'närståendes' ] }
 
 node cli.js check "./dict" sv-SE månad
 { misspelled: false, suggestions: [ 'månade', 'måna', 'månads', 'månar' ] }
  
 node cli.js check "./dict" sv-SE närståenda
 { misspelled: true, suggestions: [ 'närstående', 'närståendes' ] }
```

Its also correct in English :)

**Comment by jfmdev** [comment]
Glad to know it worked.
